### ISSUE TITLE
New Synonym request not implemented in `ProntoImplementation`

### ISSUE THREAD

**Issue by hrshdhgd** [INCATools/ontology-access-kit#208]
When I run 
`poetry run runoak -i fbbt.obo apply "create synonym 'ab' for FBbt:00003004"`

I get an `NotImplementedError`:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/oak/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/oak/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/oak/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/oak/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/oak/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/HHegde/Desktop/gitRepo/INCATools/ontology-access-kit/src/oaklib/cli.py", line 2401, in apply
    impl.apply_patch(change)
  File "/Users/HHegde/Desktop/gitRepo/INCATools/ontology-access-kit/src/oaklib/implementations/pronto/pronto_implementation.py", line 526, in apply_patch
    raise NotImplementedError
NotImplementedError
```

After debugging, it seemed like there was [no code ](https://github.com/INCATools/ontology-access-kit/blob/80528b66cf70220b854121217e2c28f44b1020b7/src/oaklib/implementations/pronto/pronto_implementation.py#L507)to address a `patch` when it was of type `kgcl.NewSynonym` as in this case.

Solution:
```
elif isinstance(patch, kgcl.NewSynonym):
            t = self._entity(patch.about_node, strict=True)
            t.add_synonym(description=patch.new_value, scope="RELATED")
```

I am not too sure about the value of `scope` but for now I have it as `RELATED`. I will have a PR ready soon.

**Comment by hrshdhgd** [comment]
Thoughts @cmungall , @matentzn ?

**Comment by hrshdhgd** [comment]
The only issue I found was if there was a URI used instead of a CURIE, it throws an error stating that it should be a CURIE.
So for e.g.  if I run:

```
poetry run runoak -i fbbt.obo apply "create synonym 'ab' for <http://purl.obolibrary.org/obo/FBbt_00004751>
```

I get: 
```
File "/opt/anaconda3/envs/ontocrawler/lib/python3.9/site-packages/oaklib/implementations/pronto/pronto_implementation.py", line 177, in _entity
    raise ValueError(f"No such CURIE: {curie}")
ValueError: No such CURIE: <http://purl.obolibrary.org/obo/FBbt_00004751>
```

**Comment by cmungall** [comment]
There are some things that needed fixed in the upstream kgcl lib to do with
curie handling
