### ISSUE TITLE
bioportal tests no longer pass

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#251]
Hmm, even though #224 passed tests, now on main the bioportal tests fail

test_ancestors:

```
Error
Traceback (most recent call last):
  File "/Users/cjm/repos/ontology-access-kit/tests/test_implementations/test_bioportal.py", line 58, in test_ancestors
    ancestors = list(self.impl.ancestors(VACUOLE))
  File "/Users/cjm/repos/ontology-access-kit/src/oaklib/implementations/ontoportal/ontoportal_implementation_base.py", line 247, in ancestors
    quoted_uri = quote(uri, safe="")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/parse.py", line 869, in quote
    return quote_from_bytes(string, safe)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/parse.py", line 894, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

Also on CLI

```
✗ runoak -i bioportal:ceph annotate "tentacle"

Traceback (most recent call last):
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/bin/runoak", line 5, in <module>
    main()
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cjm/repos/ontology-access-kit/src/oaklib/cli.py", line 921, in annotate
    for ann in impl.annotate_text(text, configuration):
  File "/Users/cjm/repos/ontology-access-kit/src/oaklib/implementations/ontoportal/ontoportal_implementation_base.py", line 150, in _annotator_json_to_results
    object_id=self.uri_to_curie(ac_obj["@id"]),
  File "/Users/cjm/repos/ontology-access-kit/src/oaklib/interfaces/basic_ontology_interface.py", line 165, in uri_to_curie
    raise ValueError(
ValueError: BioportalImplementation.prefix_map() does not support compressing http://purl.obolibrary.org/obo/CEPH_0000256.
This ontology interface contains 0 prefixes:
```

**Comment by cmungall** [comment]
OK, this is a local thing, #252 passes, odd...
