### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources' caused by class_resolver dependency

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#412]
When running from poetry:

```
✗ runoak --help
Traceback (most recent call last):
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/bin/runoak", line 2, in <module>
    from oaklib.cli import main
  File "/Users/cjm/repos/ontology-access-kit/src/oaklib/__init__.py", line 7, in <module>
    from oaklib.interfaces import BasicOntologyInterface  # noqa:F401
  File "/Users/cjm/repos/ontology-access-kit/src/oaklib/interfaces/__init__.py", line 1, in <module>
    from oaklib.interfaces.basic_ontology_interface import BasicOntologyInterface
  File "/Users/cjm/repos/ontology-access-kit/src/oaklib/interfaces/basic_ontology_interface.py", line 25, in <module>
    from oaklib.interfaces.ontology_interface import OntologyInterface
  File "/Users/cjm/repos/ontology-access-kit/src/oaklib/interfaces/ontology_interface.py", line 4, in <module>
    from oaklib.resource import OntologyResource
  File "/Users/cjm/repos/ontology-access-kit/src/oaklib/resource.py", line 5, in <module>
    from class_resolver import HintOrType
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/class_resolver/__init__.py", line 48, in <module>
    from .api import (
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/class_resolver/api.py", line 10, in <module>
    from .base import BaseResolver
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/class_resolver/base.py", line 9, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

can be isolated to:

```
>>> from class_resolver import HintOrType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/class_resolver/__init__.py", line 48, in <module>
    from .api import (
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/class_resolver/api.py", line 10, in <module>
    from .base import BaseResolver
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/class_resolver/base.py", line 9, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

I am not sure I fully understand. I can't replicate this with a new poetry project with only class_resolver as a dependency. pkg_resources should be part of the standard distribution

https://setuptools.pypa.io/en/latest/pkg_resources.html
says

Attention

Use of pkg_resources is discouraged in favor of [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Please consider using those libraries instead of pkg_resources.

**Comment by cmungall** [comment]
My workaround is

```
poetry shell
python3 -m pip install --upgrade setuptools
```

but this is not ideal
