### ISSUE TITLE
External plugins for `oaklib` do not work anymore

### ISSUE THREAD

**Issue by hrshdhgd** [INCATools/ontology-access-kit#530]
I created a project from scratch following the [`instructions in the documentation`](https://incatools.github.io/ontology-access-kit/howtos/write-a-plugin.html) and It seems to not recognize the custom descriptor. It gives me the error:
```
KeyError: "Invalid OntologyInterface name: oger. Valid choices are: ['abstractsparql', 'aggregator', 'agroportal', 'associationproviderinterface', 'basicontologyinterface', 'bioportal', 'classenrichmentcalculationinterface', 'cx', 'differinterface', 'dumperinterface', 'ecoportal', 'funowl', 'gilda', 'kgx', 'lov', 'mappingproviderinterface', 'matportal', 'mergeinterface', 'metadatainterface', 'ndexbio', 'oak', 'oakmetamodel', 'obograph', 'obographinterface', 'obolegacyinterface', 'obolibrary', 'ols', 'ontobee', 'owlinterface', 'patcherinterface', 'pronto', 'prontolib', 'rdfinterface', 'rdflib', 'relationgraphinterface', 'searchinterface', 'semanticsimilarityinterface', 'simpleobo', 'sparql', 'sql', 'sqlite', 'subsetterinterface', 'summarystatisticsinterface', 'taxonconstraintinterface', 'textannotatorinterface', 'tibols', 'translator', 'ubergraph', 'validatorinterface', 'wikidata']"
```

I tried to create a new one from scratch because an existing plugin `oakx-oger` worked in the past. I updated to the latest versions of `poetry` and `oaklib` and it suddenly stopped working.

Another plugin `oakx-spacy` works fine but it is running version 0.2.6 of `oaklib` and `poetry` v 1.4.1.

**Comment by hrshdhgd** [comment]
Fulle stack error:
```
Traceback (most recent call last):
...
  File "../envs/oakx-oger/lib/python3.9/site-packages/oaklib/cli.py", line 887, in main
    settings.impl = get_adapter(input)
  File "../envs/oakx-oger/lib/python3.9/site-packages/oaklib/selector.py", line 106, in get_adapter
    res = get_resource_from_shorthand(descriptor, format)
  File "../envs/oakx-oger/lib/python3.9/site-packages/oaklib/selector.py", line 316, in get_resource_from_shorthand
    impl_class = get_implementation_class_from_scheme(scheme)
  File "../envs/oakx-oger/lib/python3.9/site-packages/oaklib/selector.py", line 233, in get_implementation_class_from_scheme
    return get_implementation_resolver().lookup(scheme)
  File "../envs/oakx-oger/lib/python3.9/site-packages/class_resolver/api.py", line 176, in lookup
    return get_cls(
  File "../envs/oakx-oger/lib/python3.9/site-packages/class_resolver/api.py", line 378, in get_cls
    raise KeyError(
KeyError: "Invalid OntologyInterface name: oger. Valid choices are: ['abstractsparql', 'aggregator', 'agroportal', 'associationproviderinterface', 'basicontologyinterface', 'bioportal', 'classenrichmentcalculationinterface', 'cx', 'differinterface', 'dumperinterface', 'ecoportal', 'funowl', 'gilda', 'kgx', 'lov', 'mappingproviderinterface', 'matportal', 'mergeinterface', 'metadatainterface', 'ndexbio', 'oak', 'oakmetamodel', 'obograph', 'obographinterface', 'obolegacyinterface', 'obolibrary', 'ols', 'ontobee', 'owlinterface', 'patcherinterface', 'pronto', 'prontolib', 'rdfinterface', 'rdflib', 'relationgraphinterface', 'searchinterface', 'semanticsimilarityinterface', 'simpleobo', 'sparql', 'sql', 'sqlite', 'subsetterinterface', 'summarystatisticsinterface', 'taxonconstraintinterface', 'textannotatorinterface', 'tibols', 'translator', 'ubergraph', 'validatorinterface', 'wikidata']"
```

**Comment by hrshdhgd** [comment]
For now I have rolled back poetry to 1.4.0 and oaklib to 0.2.6 and thing seem to work.

**Comment by cmungall** [comment]
Thanks!

However, we really really do not want to be pinning specific versions. OAK is a general purpose library and if we pin a core library like setuptools this is highly likely to conflict with something else in a users' dependency chain

**Comment by justaddcoffee** [comment]
Pinning is suboptimal, but I think though that until we fix the problem b/t setuptools and class-resolver, all oak plugins will be broken (right?)

**Comment by pkalita-lbl** [comment]
Just to add a little nuance to the problem statement here. I can _use_ oak plugins from _other_ projects. I run into the issue when I try to use the plugin from within the plugin project itself. To wit:

```shell
# create a new project
poetry new --src test_oak
cd test_oak

# set up the venv
poetry install

# add the latest oaklib
poetry add oaklib

# I have oakx-oger checked out locally and I updated its pyproject.toml file to allow oaklib >= 0.2.0
poetry add ../oakx-oger --editable

# this works for me
poetry run runoak -i oger:sqlite:obo:envo annotate cultured organisms polar ecosystems atmospheric gas exchange
```
