### ISSUE TITLE
problem installing with latest oaklib 0.5.2

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#552]
```
✗ ontogpt  enrichment -r sqlite:obo:hgnc  -U tests/input/genesets/sensory-ataxia.yaml
Traceback (most recent call last):
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/ontogpt-KHJsTWkT-py3.10/bin/ontogpt", line 3, in <module>
    from ontogpt.cli import main
  File "/Users/cjm/repos/ontogpt/src/ontogpt/cli.py", line 15, in <module>
    from oaklib import get_adapter
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/ontogpt-KHJsTWkT-py3.10/lib/python3.10/site-packages/oaklib/__init__.py", line 9, in <module>
    from oaklib.selector import get_adapter, get_implementation_from_shorthand  # noqa:F401
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/ontogpt-KHJsTWkT-py3.10/lib/python3.10/site-packages/oaklib/selector.py", line 15, in <module>
    from oaklib.implementations.funowl.funowl_implementation import FunOwlImplementation
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/ontogpt-KHJsTWkT-py3.10/lib/python3.10/site-packages/oaklib/implementations/__init__.py", line 39, in <module>
    from oaklib.implementations.rustsim.rustsim_implementation import RustSimImplementation
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/ontogpt-KHJsTWkT-py3.10/lib/python3.10/site-packages/oaklib/implementations/rustsim/rustsim_implementation.py", line 10, in <module>
    from rustsim import get_intersection, jaccard_similarity, mrca_and_score
ModuleNotFoundError: No module named 'rustsim'
```

**Comment by cmungall** [comment]
EITHER rustsim should be an extra, in which case there absolutely must be no static imports

OR it's a bona fide dependency

**Comment by caufieldjh** [comment]
Let's just make it a full dependency.
