### ISSUE TITLE
Similarity with `semsimian` raises an error from `curies`

### ISSUE THREAD

**Issue by caufieldjh** [INCATools/ontology-access-kit#606]
Running the similarity command with semsimian raises `curies.api.DuplicateURIPrefixes` with any parameters:
```
$ runoak -i semsimian:sqlite:obo:bfo similarity -p i,p .all @ .all
curies.api.DuplicateURIPrefixes: Duplicate URI prefixes:

https://icd.who.int/browse10/2019/en#/:
        prefix='ICD10WHO' uri_prefix='https://icd.who.int/browse10/2019/en#/' prefix_synonyms=[] uri_prefix_synonyms=[]
        prefix='icd10who' uri_prefix='https://icd.who.int/browse10/2019/en#/' prefix_synonyms=[] uri_prefix_synonyms=[]
```

Running `runoak -i semsimian:sqlite:obo:bfo similarity --help` does the same.

Running the same command without the semsimian prefix in the input slug runs as expected.

**Comment by caufieldjh** [comment]
With verbose:
```
$ runoak -vvv -i semsimian:sqlite:obo:bfo similarity -p i,p .all @ .all
INFO:root:Setting other_languages=()
INFO:root:Settings = Settings(impl=None, autosave=False, associations_type=None, preferred_language=None, other_languages=())
INFO:root:Wrapping an existing OAK implementation to fetch sqlite:obo:bfo
INFO:root:Locator: obo:bfo
INFO:root:Ensuring gunzipped for https://s3.amazonaws.com/bbop-sqlite/bfo.db.gz
INFO:root:Locator, post-processed: sqlite:////home/harry/.data/oaklib/bfo.db
curies.api.DuplicateURIPrefixes: Duplicate URI prefixes:

https://icd.who.int/browse10/2019/en#/:
        prefix='ICD10WHO' uri_prefix='https://icd.who.int/browse10/2019/en#/' prefix_synonyms=[] uri_prefix_synonyms=[]
        prefix='icd10who' uri_prefix='https://icd.who.int/browse10/2019/en#/' prefix_synonyms=[] uri_prefix_synonyms=[]
```

**Comment by caufieldjh** [comment]
Is it related to this change? https://github.com/INCATools/ontology-access-kit/commit/e8446b58d0ac70a97fb203553a104e07c384cff5

**Comment by caufieldjh** [comment]
Minimal reproduction (again, in python 3.9):
```
>>> from oaklib.implementations.semsimian.semsimian_implementation import SemSimianImplementation
>>> from oaklib.selector import get_adapter
>>> slug = "semsimian:sqlite:obo:bfo"
>>> slug = slug.replace("semsimian:", "")
>>> wrapped_adapter = get_adapter(slug)
>>> wrapped_adapter
SqlImplementation(resource=OntologyResource(slug='obo:bfo', directory=None, scheme='sqlite', format=None, url=None, readonly=False, provider=None, local=False, in_memory=False, data=None, implementation_class=<class 'oaklib.implementations.sqldb.sql_implementation.SqlImplementation'>, import_depth=None), strict=False, _multilingual=None, autosave=True, exclude_owl_top_and_bottom=True, ontology_metamodel_mapper=None, _converter=None, auto_relax_axioms=None, cache_lookups=False, _edge_index=None, _entailed_edge_index=None, functional_writer=None, _association_index=None, normalizers=[], engine=Engine(sqlite:////home/harry/.data/oaklib/bfo.db), _session=None, _connection=None, _ontology_metadata_model=None, _prefix_map=None, _information_content_cache=None, _relationships_by_subject_index=None, max_items_for_in_clause=1000, can_store_associations=False)
>>> import inspect
>>> methods = dict(inspect.getmembers(wrapped_adapter))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/inspect.py", line 351, in getmembers
    value = getattr(object, key)
  File "/home/harry/ontology-access-kit/src/oaklib/interfaces/basic_ontology_interface.py", line 202, in converter
    self._converter = curies.Converter.from_prefix_map(self.prefix_map())
  File "/home/harry/ontology-access-kit/.venv/lib/python3.9/site-packages/curies/api.py", line 539, in from_prefix_map
    return cls(
  File "/home/harry/ontology-access-kit/.venv/lib/python3.9/site-packages/curies/api.py", line 321, in __init__
    raise DuplicateURIPrefixes(duplicate_uri_prefixes)
curies.api.DuplicateURIPrefixes: Duplicate URI prefixes:

https://icd.who.int/browse10/2019/en#/:
        prefix='ICD10WHO' uri_prefix='https://icd.who.int/browse10/2019/en#/' prefix_synonyms=[] uri_prefix_synonyms=[]
        prefix='icd10who' uri_prefix='https://icd.who.int/browse10/2019/en#/' prefix_synonyms=[] uri_prefix_synonyms=[]
```

So I think this is what happens:
* With SemsimianImplementation, any init calls `__post_init__`, which retrieves the methods from whatever the input slug is wrapping (like `sqlite:obo:bfo` above). The parent methods don't do that. In this case, `inspect.getmembers` does a dynamic lookup to get the value of each key, and despite `_converter` being `None` in the wrapped_adapter, `SqlImplementation` is still a  child class of `BasicOntologyInterface`, and _that_ sets a `_converter` here: https://github.com/INCATools/ontology-access-kit/blob/e8446b58d0ac70a97fb203553a104e07c384cff5/src/oaklib/interfaces/basic_ontology_interface.py#L190-L203.
* Assigning `_converter` still happens even without using the `semsimian` implementation, that just doesn't call inspect.getmembers to retrieve a methods list.
* Newer versions of `inspect` have a `getmembers_static` method that may avoid this issue.

So why does the prefix map seem to be broken?
* Getting the default prefix map from the following returns a dict without the supposedly duplicate prefix or URI:
```
>>> from oaklib.interfaces.basic_ontology_interface import get_default_prefix_map
>>> get_default_prefix_map()
```
* This URI doesn't appear to be in `prefixmaps` either.
* BUT...it is in the Bioregistry obo context: https://github.com/biopragmatics/bioregistry/blob/b2b3e1d43026ba02d3b6eeced52b0b98627b1429/exports/contexts/obo.context.ttl#L163
* (also related to how there's no One True Prefix for ICD10, or ICD for that matter; see https://github.com/biopragmatics/bioregistry/issues/251)

So that's a proper bijective map - where's the lowercase version coming from?

**Comment by caufieldjh** [comment]
The `SqlImplementation` inherits from `MappingProviderInterface`, and that works with lowercase versions of prefixes, but I'm not sure if that's actually called in this case.

**Comment by caufieldjh** [comment]
Error still happens if I:
* Remove all downloaded sql ontologies (from ~/.data/oaklib/)
* Use a new venv through poetry
* Use a fresh clone of the repo

This is all on python 3.9.5.

Strangely, I get the same error when running `runoak -i sqlite:obo:bfo ontology-metadata --all`

**Comment by caufieldjh** [comment]
Using the pdb debugger to get to the point in BasicOntologyInterface where 
```
self._converter = curies.Converter.from_prefix_map(self.prefix_map())
```
shows that self.prefix_map() _does contain the duplicate uri prefix mapping_.

**Comment by caufieldjh** [comment]
It looks like this issue is common to any of the semantic-sql prebuilt OBO ontologies - @hrshdhgd built a fresh db version of BFO directly from the owl and it parsed as expected.

**Comment by cthoyt** [comment]
@caufieldjh is it clear what the error message in CURIEs means? I think that it's completely reasonable to assume case sensitive bijection by default, so I wonder if the fact that the issue here is coming up from case insensitivity is because it's not clear how `curies` works

**Comment by caufieldjh** [comment]
I don't think there's any issue with the error itself, though if I was an OAK user unfamiliar with `curies` then I would be pretty baffled. I also think it's perfectly fine to assume bijectivity in the prefixmap, including with casing. Here, we clearly have a prefixmap violating that assumption and it Should Not Be, and there also isn't any user-accessible alternative (it isn't like I can pass an alternative prefixmap context to SqlImplementation)

**Comment by caufieldjh** [comment]
> it isn't like I can pass an alternative prefixmap context to SqlImplementation

Realized after this that the `--named-prefix-map` [CLI arg exists](https://incatools.github.io/ontology-access-kit/cli.html#cmdoption-runoak-named-prefix-map), so that is, in fact, the other workaround

**Comment by caufieldjh** [comment]
Fixed by https://github.com/INCATools/semantic-sql/commit/ea764b1d884930723f16369f830be082da85bfb9
