### ISSUE TITLE
`AttributeError` in `TranslatorImplementation` when using node normalizer endpoint

### ISSUE THREAD

**Issue by caufieldjh** [INCATools/ontology-access-kit#662]
Discovered here in ontogpt: https://github.com/monarch-initiative/ontogpt/issues/224

Calls to the node normalizer endpoint through TranslatorImplementation lead to an `AttributeError` as the response is valid JSON but appears to just be "detail: "Not Found"", even for cases where an input CURIE really should be found.
(and even if it wasn't found, I'd expect the error to be caught).

Example:
```
$ python
Python 3.9.18 (main, Aug 25 2023, 13:20:04) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from oaklib.implementations.translator.translator_implementation import TranslatorImplementation
>>> ti = TranslatorImplementation()
>>> maps = ti.sssom_mappings("HGNC:11148")
>>> for map in maps:
...   print(maps)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/oaklib/implementations/translator/translator_implementation.py", line 62, in sssom_mappings
    equiv_identifiers = data.get("equivalent_identifiers", [])
AttributeError: 'str' object has no attribute 'get'
```

**Comment by caufieldjh** [comment]
I think there's a simple fix here:
```
NODE_NORMALIZER_ENDPOINT = "https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes"
```
needs to be
```
NODE_NORMALIZER_ENDPOINT = "https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes"
```
in
translator_implementation.py.
