### ISSUE TITLE
Breaking change in Synonymizer?

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-access-kit#748]
An ancient pipeline of ours just started breaking due to some change in synonymizer:

```
python ../scripts/match-mondo-sources-all-lexical.py run tmp/merged.db \
        -c metadata/mondo.sssom.config.yml \
        -r config/mondo-match-rules.yaml \
        --rejects ../mappings/rejected-mappings.tsv \
        -o ../mappings/mondo-sources-all-lexical.sssom.tsv
/usr/local/lib/python3.10/dist-packages/sssom/util.py:168: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("", np.nan, inplace=True)
Traceback (most recent call last):
  File "/work/src/ontology/../scripts/match-mondo-sources-all-lexical.py", line 151, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/work/src/ontology/../scripts/match-mondo-sources-all-lexical.py", line 116, in run
    ruleset = load_mapping_rules(rules)
  File "/usr/local/lib/python3.10/dist-packages/oaklib/utilities/lexical/lexical_indexer.py", line 518, in load_mapping_rules
    return yaml_loader.load(path, target_class=MappingRuleCollection)
  File "/usr/local/lib/python3.10/dist-packages/linkml_runtime/loaders/loader_root.py", line 76, in load
    results = self.load_any(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/linkml_runtime/loaders/yaml_loader.py", line 42, in load_any
    return self._construct_target_class(data_as_dict, target_class)
  File "/usr/local/lib/python3.10/dist-packages/linkml_runtime/loaders/loader_root.py", line 137, in _construct_target_class
    return target_class(**data_as_dict)
  File "<string>", line 5, in __init__
  File "/usr/local/lib/python3.10/dist-packages/oaklib/datamodels/mapping_rules_datamodel.py", line 86, in __post_init__
    self.rules = [v if isinstance(v, MappingRule) else MappingRule(**as_dict(v)) for v in self.rules]
  File "/usr/local/lib/python3.10/dist-packages/oaklib/datamodels/mapping_rules_datamodel.py", line 86, in <listcomp>
    self.rules = [v if isinstance(v, MappingRule) else MappingRule(**as_dict(v)) for v in self.rules]
  File "<string>", line 8, in __init__
  File "/usr/local/lib/python3.10/dist-packages/oaklib/datamodels/mapping_rules_datamodel.py", line 126, in __post_init__
    self.synonymizer = Synonymizer(**as_dict(self.synonymizer))
  File "<string>", line 11, in __init__
  File "/usr/local/lib/python3.10/dist-packages/oaklib/datamodels/mapping_rules_datamodel.py", line 435, in __post_init__
    super().__post_init__(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/linkml_runtime/utils/yamlutils.py", line 53, in __post_init__
    raise ValueError('\n'.join(messages))
ValueError:  Unknown argument: the_rule = 'Remove box brackets bound info from the
make[1]: *** [mondo-ingest.Makefile:439: ../mappings/mondo-sources-all-lexical.sssom.tsv] Error 1
rm imports/ro_terms_combined.txt
```

This is blocking an ODK release, but I am not allowed to work on anything atm due to my commitments with the paper writing. @cmungall does this ring a bell? No changes on Mondo ingest side of things.

**Comment by matentzn** [comment]
cc @twhetzel

**Comment by gouttegd** [comment]
Yes, it’s a breaking change introduced in 0.6.0 with #728.

Basically in synonymizer rules, the old `the_rule` key has been replaced by a `description` key. So:

```yaml
- synonymizer:
    the_rule: Remove box brackets bound info from the label.
    match: r'\[[^)]*\]'
    match_scope: "*"
    replacement: ""
```

must be replaced with:

```yaml
- synonymizer:
    description: Remove box brackets bound info from the label.
    match: r'\[[^)]*\]'
    match_scope: "*"
    replacement: ""
```

Ideally the parser should, at least for a while, accept `the_rule` as an alias for `description` to avoid breaking existing rules, but I an not sure LinkML offers an easy way to do that.

**Comment by matentzn** [comment]
You are a star man.. Thanks @gouttegd testing this right now, if its just that I will go ahead with a maintenance release.
